[2025-10-17T20:53:50.207+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test manual__2025-10-17T20:53:32.974715+00:00 [queued]>
[2025-10-17T20:53:50.215+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test manual__2025-10-17T20:53:32.974715+00:00 [queued]>
[2025-10-17T20:53:50.216+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T20:53:50.228+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_test> on 2025-10-17 20:53:32.974715+00:00
[2025-10-17T20:53:50.232+0000] {standard_task_runner.py:57} INFO - Started process 201 to run task
[2025-10-17T20:53:50.235+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_test', 'manual__2025-10-17T20:53:32.974715+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp88mmapcr']
[2025-10-17T20:53:50.239+0000] {standard_task_runner.py:85} INFO - Job 13: Subtask dbt_test
[2025-10-17T20:53:50.255+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T20:53:50.300+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_test manual__2025-10-17T20:53:32.974715+00:00 [running]> on host eb8a9840e92a
[2025-10-17T20:53:50.382+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T20:53:32.974715+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T20:53:32.974715+00:00'
[2025-10-17T20:53:50.384+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T20:53:50.385+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt test --profiles-dir .']
[2025-10-17T20:53:50.394+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T20:53:50.396+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T20:53:50.397+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-17T20:53:50.409+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-17T20:53:50.413+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dbt_run_pipeline, task_id=dbt_test, execution_date=20251017T205332, start_date=20251017T205350, end_date=20251017T205350
[2025-10-17T20:53:50.425+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 13 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 201)
[2025-10-17T20:53:50.460+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-17T20:53:50.479+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
