[2025-10-17T21:17:24.063+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test manual__2025-10-17T21:17:05.130390+00:00 [queued]>
[2025-10-17T21:17:24.070+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test manual__2025-10-17T21:17:05.130390+00:00 [queued]>
[2025-10-17T21:17:24.071+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:17:24.082+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_test> on 2025-10-17 21:17:05.130390+00:00
[2025-10-17T21:17:24.086+0000] {standard_task_runner.py:57} INFO - Started process 219 to run task
[2025-10-17T21:17:24.089+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_test', 'manual__2025-10-17T21:17:05.130390+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpjhx4aomh']
[2025-10-17T21:17:24.093+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask dbt_test
[2025-10-17T21:17:24.109+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:17:24.145+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_test manual__2025-10-17T21:17:05.130390+00:00 [running]> on host 10529ec04042
[2025-10-17T21:17:24.217+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-10-17T21:17:05.130390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-17T21:17:05.130390+00:00'
[2025-10-17T21:17:24.219+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:17:24.220+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt test --profiles-dir /opt/***/dbt']
[2025-10-17T21:17:24.228+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:17:27.311+0000] {subprocess.py:93} INFO - [0m21:17:27  Running with dbt=1.7.0
[2025-10-17T21:17:27.644+0000] {subprocess.py:93} INFO - [0m21:17:27  Registered adapter: postgres=1.7.0
[2025-10-17T21:17:27.734+0000] {subprocess.py:93} INFO - [0m21:17:27  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-10-17T21:17:27.737+0000] {subprocess.py:93} INFO - [0m21:17:27
[2025-10-17T21:17:27.738+0000] {subprocess.py:93} INFO - [0m21:17:27  Nothing to do. Try checking your model configs and model specification args
[2025-10-17T21:17:28.634+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:17:28.666+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_test, execution_date=20251017T211705, start_date=20251017T211724, end_date=20251017T211728
[2025-10-17T21:17:28.697+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:17:28.714+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
