[2025-10-16T13:28:14.043+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_seed manual__2025-10-16T13:28:11.430311+00:00 [queued]>
[2025-10-16T13:28:14.054+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_seed manual__2025-10-16T13:28:11.430311+00:00 [queued]>
[2025-10-16T13:28:14.054+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-16T13:28:14.069+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_seed> on 2025-10-16 13:28:11.430311+00:00
[2025-10-16T13:28:14.074+0000] {standard_task_runner.py:57} INFO - Started process 187 to run task
[2025-10-16T13:28:14.078+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_seed', 'manual__2025-10-16T13:28:11.430311+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpyrbdxdc4']
[2025-10-16T13:28:14.082+0000] {standard_task_runner.py:85} INFO - Job 6: Subtask dbt_seed
[2025-10-16T13:28:14.102+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-16T13:28:14.151+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_seed manual__2025-10-16T13:28:11.430311+00:00 [running]> on host 2e5e3d4f13d1
[2025-10-16T13:28:14.246+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_seed' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T13:28:11.430311+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-10-16T13:28:11.430311+00:00'
[2025-10-16T13:28:14.249+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-16T13:28:14.250+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt seed --profiles-dir .']
[2025-10-16T13:28:14.260+0000] {subprocess.py:86} INFO - Output:
[2025-10-16T13:28:14.263+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-16T13:28:14.264+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-16T13:28:14.277+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-16T13:28:14.283+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dbt_run_pipeline, task_id=dbt_seed, execution_date=20251016T132811, start_date=20251016T132814, end_date=20251016T132814
[2025-10-16T13:28:14.312+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 6 for task dbt_seed (Bash command failed. The command returned a non-zero exit code 1.; 187)
[2025-10-16T13:28:14.346+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-16T13:28:14.379+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
