[2025-10-17T00:51:46.602+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T00:51:46.614+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T00:51:46.615+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T00:51:46.639+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_init> on 2025-10-16 00:00:00+00:00
[2025-10-17T00:51:46.650+0000] {standard_task_runner.py:57} INFO - Started process 3841 to run task
[2025-10-17T00:51:46.658+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_init', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp1qxt92yd']
[2025-10-17T00:51:46.665+0000] {standard_task_runner.py:85} INFO - Job 7: Subtask dbt_init
[2025-10-17T00:51:46.711+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T00:51:46.813+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [running]> on host 2e5e3d4f13d1
[2025-10-17T00:51:46.934+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_init' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T00:51:46.936+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T00:51:46.940+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt debug --profiles-dir . || true']
[2025-10-17T00:51:46.954+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T00:51:46.964+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T00:51:46.965+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T00:51:47.012+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_init, execution_date=20251016T000000, start_date=20251017T005146, end_date=20251017T005147
[2025-10-17T00:51:47.051+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T00:51:47.077+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-17T20:11:27.449+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T20:11:27.458+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T20:11:27.459+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T20:11:27.470+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_init> on 2025-10-16 00:00:00+00:00
[2025-10-17T20:11:27.474+0000] {standard_task_runner.py:57} INFO - Started process 228 to run task
[2025-10-17T20:11:27.479+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_init', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmplc_bsroz']
[2025-10-17T20:11:27.484+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask dbt_init
[2025-10-17T20:11:27.504+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T20:11:27.547+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [running]> on host 73cb6ab1cd9d
[2025-10-17T20:11:27.661+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_init' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T20:11:27.663+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T20:11:27.664+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt debug --profiles-dir . || true']
[2025-10-17T20:11:27.675+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T20:11:27.677+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T20:11:27.678+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T20:11:27.707+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_init, execution_date=20251016T000000, start_date=20251017T201127, end_date=20251017T201127
[2025-10-17T20:11:27.739+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T20:11:27.769+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-17T20:28:00.019+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T20:28:00.027+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T20:28:00.027+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T20:28:00.041+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_init> on 2025-10-16 00:00:00+00:00
[2025-10-17T20:28:00.045+0000] {standard_task_runner.py:57} INFO - Started process 178 to run task
[2025-10-17T20:28:00.049+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_init', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpjt45bu_y']
[2025-10-17T20:28:00.053+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask dbt_init
[2025-10-17T20:28:00.071+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T20:28:00.113+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [running]> on host 53e4ea1d8d00
[2025-10-17T20:28:00.207+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_init' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T20:28:00.209+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T20:28:00.211+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt debug --profiles-dir . || true']
[2025-10-17T20:28:00.220+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T20:28:00.223+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T20:28:00.223+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T20:28:00.252+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_init, execution_date=20251016T000000, start_date=20251017T202800, end_date=20251017T202800
[2025-10-17T20:28:00.269+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T20:28:00.299+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-17T20:36:16.205+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T20:36:16.213+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T20:36:16.213+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T20:36:16.224+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_init> on 2025-10-16 00:00:00+00:00
[2025-10-17T20:36:16.228+0000] {standard_task_runner.py:57} INFO - Started process 173 to run task
[2025-10-17T20:36:16.231+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_init', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp1mkt9m9n']
[2025-10-17T20:36:16.234+0000] {standard_task_runner.py:85} INFO - Job 2: Subtask dbt_init
[2025-10-17T20:36:16.252+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T20:36:16.289+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [running]> on host 00b52ae6051a
[2025-10-17T20:36:16.370+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_init' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T20:36:16.371+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T20:36:16.372+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt debug --profiles-dir . || true']
[2025-10-17T20:36:16.382+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T20:36:16.384+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T20:36:16.385+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T20:36:16.410+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_init, execution_date=20251016T000000, start_date=20251017T203616, end_date=20251017T203616
[2025-10-17T20:36:16.452+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T20:36:16.480+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:03:41.878+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:03:41.887+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:03:41.887+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:03:41.898+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_init> on 2025-10-16 00:00:00+00:00
[2025-10-17T21:03:41.901+0000] {standard_task_runner.py:57} INFO - Started process 198 to run task
[2025-10-17T21:03:41.906+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_init', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp4sm0u7fq']
[2025-10-17T21:03:41.909+0000] {standard_task_runner.py:85} INFO - Job 15: Subtask dbt_init
[2025-10-17T21:03:41.925+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:03:41.960+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [running]> on host b0360591ae5e
[2025-10-17T21:03:42.040+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_init' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T21:03:42.042+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:03:42.043+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt debug --profiles-dir . || true']
[2025-10-17T21:03:42.052+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:03:42.054+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T21:03:42.054+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:03:42.078+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_init, execution_date=20251016T000000, start_date=20251017T210341, end_date=20251017T210342
[2025-10-17T21:03:42.126+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:03:42.156+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:04:40.333+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:04:40.342+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:04:40.343+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:04:40.355+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_init> on 2025-10-16 00:00:00+00:00
[2025-10-17T21:04:40.359+0000] {standard_task_runner.py:57} INFO - Started process 240 to run task
[2025-10-17T21:04:40.363+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_init', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmp2mv320la']
[2025-10-17T21:04:40.370+0000] {standard_task_runner.py:85} INFO - Job 21: Subtask dbt_init
[2025-10-17T21:04:40.384+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:04:40.418+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [running]> on host b0360591ae5e
[2025-10-17T21:04:40.483+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_init' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T21:04:40.484+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:04:40.485+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt debug --profiles-dir . || true']
[2025-10-17T21:04:40.492+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:04:40.494+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T21:04:40.495+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:04:40.519+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_init, execution_date=20251016T000000, start_date=20251017T210440, end_date=20251017T210440
[2025-10-17T21:04:40.542+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:04:40.566+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:17:25.165+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:17:25.173+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:17:25.174+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:17:25.186+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_init> on 2025-10-16 00:00:00+00:00
[2025-10-17T21:17:25.190+0000] {standard_task_runner.py:57} INFO - Started process 222 to run task
[2025-10-17T21:17:25.193+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_init', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpaahbh4d5']
[2025-10-17T21:17:25.196+0000] {standard_task_runner.py:85} INFO - Job 32: Subtask dbt_init
[2025-10-17T21:17:25.212+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:17:25.257+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_init scheduled__2025-10-16T00:00:00+00:00 [running]> on host 10529ec04042
[2025-10-17T21:17:25.354+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_init' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T21:17:25.356+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:17:25.358+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt debug --profiles-dir . || true']
[2025-10-17T21:17:25.385+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:17:28.442+0000] {subprocess.py:93} INFO - [0m21:17:28  Running with dbt=1.7.0
[2025-10-17T21:17:28.444+0000] {subprocess.py:93} INFO - [0m21:17:28  dbt version: 1.7.0
[2025-10-17T21:17:28.445+0000] {subprocess.py:93} INFO - [0m21:17:28  python version: 3.11.5
[2025-10-17T21:17:28.446+0000] {subprocess.py:93} INFO - [0m21:17:28  python path: /usr/local/bin/python
[2025-10-17T21:17:28.447+0000] {subprocess.py:93} INFO - [0m21:17:28  os info: Linux-6.10.14-linuxkit-x86_64-with-glibc2.31
[2025-10-17T21:17:28.640+0000] {subprocess.py:93} INFO - [0m21:17:28  Using profiles dir at .
[2025-10-17T21:17:28.640+0000] {subprocess.py:93} INFO - [0m21:17:28  Using profiles.yml file at ./profiles.yml
[2025-10-17T21:17:28.641+0000] {subprocess.py:93} INFO - [0m21:17:28  Using dbt_project.yml file at /opt/***/dbt/dbt_project.yml
[2025-10-17T21:17:28.642+0000] {subprocess.py:93} INFO - [0m21:17:28  adapter type: postgres
[2025-10-17T21:17:28.642+0000] {subprocess.py:93} INFO - [0m21:17:28  adapter version: 1.7.0
[2025-10-17T21:17:28.736+0000] {subprocess.py:93} INFO - [0m21:17:28  Configuration:
[2025-10-17T21:17:28.737+0000] {subprocess.py:93} INFO - [0m21:17:28    profiles.yml file [[32mOK found and valid[0m]
[2025-10-17T21:17:28.738+0000] {subprocess.py:93} INFO - [0m21:17:28    dbt_project.yml file [[32mOK found and valid[0m]
[2025-10-17T21:17:28.739+0000] {subprocess.py:93} INFO - [0m21:17:28  Required dependencies:
[2025-10-17T21:17:28.742+0000] {subprocess.py:93} INFO - [0m21:17:28   - git [[31mERROR[0m]
[2025-10-17T21:17:28.743+0000] {subprocess.py:93} INFO - 
[2025-10-17T21:17:28.743+0000] {subprocess.py:93} INFO - [0m21:17:28  Connection:
[2025-10-17T21:17:28.744+0000] {subprocess.py:93} INFO - [0m21:17:28    host: postgres
[2025-10-17T21:17:28.745+0000] {subprocess.py:93} INFO - [0m21:17:28    port: 5432
[2025-10-17T21:17:28.746+0000] {subprocess.py:93} INFO - [0m21:17:28    user: ***
[2025-10-17T21:17:28.748+0000] {subprocess.py:93} INFO - [0m21:17:28    database: ***
[2025-10-17T21:17:28.749+0000] {subprocess.py:93} INFO - [0m21:17:28    schema: public
[2025-10-17T21:17:28.749+0000] {subprocess.py:93} INFO - [0m21:17:28    connect_timeout: 10
[2025-10-17T21:17:28.750+0000] {subprocess.py:93} INFO - [0m21:17:28    role: None
[2025-10-17T21:17:28.751+0000] {subprocess.py:93} INFO - [0m21:17:28    search_path: None
[2025-10-17T21:17:28.752+0000] {subprocess.py:93} INFO - [0m21:17:28    keepalives_idle: 0
[2025-10-17T21:17:28.753+0000] {subprocess.py:93} INFO - [0m21:17:28    sslmode: None
[2025-10-17T21:17:28.754+0000] {subprocess.py:93} INFO - [0m21:17:28    sslcert: None
[2025-10-17T21:17:28.755+0000] {subprocess.py:93} INFO - [0m21:17:28    sslkey: None
[2025-10-17T21:17:28.755+0000] {subprocess.py:93} INFO - [0m21:17:28    sslrootcert: None
[2025-10-17T21:17:28.756+0000] {subprocess.py:93} INFO - [0m21:17:28    application_name: dbt
[2025-10-17T21:17:28.757+0000] {subprocess.py:93} INFO - [0m21:17:28    retries: 1
[2025-10-17T21:17:28.758+0000] {subprocess.py:93} INFO - [0m21:17:28  Registered adapter: postgres=1.7.0
[2025-10-17T21:17:28.770+0000] {subprocess.py:93} INFO - [0m21:17:28    Connection test: [[32mOK connection ok[0m]
[2025-10-17T21:17:28.771+0000] {subprocess.py:93} INFO - 
[2025-10-17T21:17:28.771+0000] {subprocess.py:93} INFO - [0m21:17:28  [31m1 check failed:[0m
[2025-10-17T21:17:28.772+0000] {subprocess.py:93} INFO - [0m21:17:28  Error from git --help: User does not have permissions for this command: "git"
[2025-10-17T21:17:28.772+0000] {subprocess.py:93} INFO - 
[2025-10-17T21:17:29.600+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:17:29.628+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_init, execution_date=20251016T000000, start_date=20251017T211725, end_date=20251017T211729
[2025-10-17T21:17:29.681+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:17:29.734+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
