[2025-10-17T21:03:56.883+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:03:56.891+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:03:56.892+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:03:56.904+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_test> on 2025-10-16 00:00:00+00:00
[2025-10-17T21:03:56.909+0000] {standard_task_runner.py:57} INFO - Started process 221 to run task
[2025-10-17T21:03:56.913+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_test', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpbg_0i384']
[2025-10-17T21:03:56.917+0000] {standard_task_runner.py:85} INFO - Job 18: Subtask dbt_test
[2025-10-17T21:03:56.935+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:03:56.977+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_test scheduled__2025-10-16T00:00:00+00:00 [running]> on host b0360591ae5e
[2025-10-17T21:03:57.054+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T21:03:57.055+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:03:57.056+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt test --profiles-dir .']
[2025-10-17T21:03:57.065+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:03:57.067+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T21:03:57.068+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-17T21:03:57.080+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-17T21:03:57.085+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dbt_run_pipeline, task_id=dbt_test, execution_date=20251016T000000, start_date=20251017T210356, end_date=20251017T210357
[2025-10-17T21:03:57.098+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 221)
[2025-10-17T21:03:57.137+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-17T21:03:57.161+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:04:53.474+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:04:53.482+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:04:53.483+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:04:53.494+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_test> on 2025-10-16 00:00:00+00:00
[2025-10-17T21:04:53.498+0000] {standard_task_runner.py:57} INFO - Started process 283 to run task
[2025-10-17T21:04:53.501+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_test', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpin0l5mak']
[2025-10-17T21:04:53.505+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask dbt_test
[2025-10-17T21:04:53.520+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:04:53.559+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_test scheduled__2025-10-16T00:00:00+00:00 [running]> on host b0360591ae5e
[2025-10-17T21:04:53.630+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T21:04:53.633+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:04:53.633+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt_project && dbt test --profiles-dir .']
[2025-10-17T21:04:53.642+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:04:53.644+0000] {subprocess.py:93} INFO - /bin/bash: line 1: cd: /opt/***/dbt_project: No such file or directory
[2025-10-17T21:04:53.645+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-10-17T21:04:53.655+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-10-17T21:04:53.659+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=dbt_run_pipeline, task_id=dbt_test, execution_date=20251016T000000, start_date=20251017T210453, end_date=20251017T210453
[2025-10-17T21:04:53.670+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task dbt_test (Bash command failed. The command returned a non-zero exit code 1.; 283)
[2025-10-17T21:04:53.684+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-10-17T21:04:53.703+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-10-17T21:17:41.288+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:17:41.296+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_run_pipeline.dbt_test scheduled__2025-10-16T00:00:00+00:00 [queued]>
[2025-10-17T21:17:41.296+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-10-17T21:17:41.306+0000] {taskinstance.py:1380} INFO - Executing <Task(BashOperator): dbt_test> on 2025-10-16 00:00:00+00:00
[2025-10-17T21:17:41.310+0000] {standard_task_runner.py:57} INFO - Started process 249 to run task
[2025-10-17T21:17:41.313+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dbt_run_pipeline', 'dbt_test', 'scheduled__2025-10-16T00:00:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/dbt_dag.py', '--cfg-path', '/tmp/tmpwh41b27y']
[2025-10-17T21:17:41.315+0000] {standard_task_runner.py:85} INFO - Job 35: Subtask dbt_test
[2025-10-17T21:17:41.331+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.11/site-packages/***/settings.py:195 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-10-17T21:17:41.367+0000] {task_command.py:415} INFO - Running <TaskInstance: dbt_run_pipeline.dbt_test scheduled__2025-10-16T00:00:00+00:00 [running]> on host 10529ec04042
[2025-10-17T21:17:41.436+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_run_pipeline' AIRFLOW_CTX_TASK_ID='dbt_test' AIRFLOW_CTX_EXECUTION_DATE='2025-10-16T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-16T00:00:00+00:00'
[2025-10-17T21:17:41.438+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-10-17T21:17:41.439+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cd /opt/***/dbt && dbt test --profiles-dir /opt/***/dbt']
[2025-10-17T21:17:41.446+0000] {subprocess.py:86} INFO - Output:
[2025-10-17T21:17:44.210+0000] {subprocess.py:93} INFO - [0m21:17:44  Running with dbt=1.7.0
[2025-10-17T21:17:44.544+0000] {subprocess.py:93} INFO - [0m21:17:44  Registered adapter: postgres=1.7.0
[2025-10-17T21:17:44.614+0000] {subprocess.py:93} INFO - [0m21:17:44  Found 1 model, 1 seed, 0 sources, 0 exposures, 0 metrics, 401 macros, 0 groups, 0 semantic models
[2025-10-17T21:17:44.618+0000] {subprocess.py:93} INFO - [0m21:17:44
[2025-10-17T21:17:44.618+0000] {subprocess.py:93} INFO - [0m21:17:44  Nothing to do. Try checking your model configs and model specification args
[2025-10-17T21:17:45.511+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-10-17T21:17:45.538+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=dbt_run_pipeline, task_id=dbt_test, execution_date=20251016T000000, start_date=20251017T211741, end_date=20251017T211745
[2025-10-17T21:17:45.594+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-10-17T21:17:45.615+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
